// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace LT.DigitalOffice.ProjectService.Data.Provider.MsSql.Ef.Database.Migrations
{
    [DbContext(typeof(ProjectServiceDbContext))]
    [Migration("20201014143208_AddShortNameForDbProject")]
    partial class AddShortNameForDbProject
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LT.DigitalOffice.ProjectService.Models.Db.Entities.DbProject", b =>
                {
                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
